# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /users/ziyzhang/topology-research/nexullance/IT_boost/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /users/ziyzhang/topology-research/nexullance/IT_boost

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /users/ziyzhang/topology-research/nexullance/IT_boost/CMakeFiles /users/ziyzhang/topology-research/nexullance/IT_boost/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /users/ziyzhang/topology-research/nexullance/IT_boost/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main.exe

# Build rule for target.
main.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main.exe
.PHONY : main.exe

# fast build rule for target.
main.exe/fast:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/build
.PHONY : main.exe/fast

Nexullance_IT.o: Nexullance_IT.cpp.o

.PHONY : Nexullance_IT.o

# target to build an object file
Nexullance_IT.cpp.o:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/Nexullance_IT.cpp.o
.PHONY : Nexullance_IT.cpp.o

Nexullance_IT.i: Nexullance_IT.cpp.i

.PHONY : Nexullance_IT.i

# target to preprocess a source file
Nexullance_IT.cpp.i:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/Nexullance_IT.cpp.i
.PHONY : Nexullance_IT.cpp.i

Nexullance_IT.s: Nexullance_IT.cpp.s

.PHONY : Nexullance_IT.s

# target to generate assembly for a file
Nexullance_IT.cpp.s:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/Nexullance_IT.cpp.s
.PHONY : Nexullance_IT.cpp.s

helpers.o: helpers.cpp.o

.PHONY : helpers.o

# target to build an object file
helpers.cpp.o:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/helpers.cpp.o
.PHONY : helpers.cpp.o

helpers.i: helpers.cpp.i

.PHONY : helpers.i

# target to preprocess a source file
helpers.cpp.i:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/helpers.cpp.i
.PHONY : helpers.cpp.i

helpers.s: helpers.cpp.s

.PHONY : helpers.s

# target to generate assembly for a file
helpers.cpp.s:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/helpers.cpp.s
.PHONY : helpers.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/main.cpp.s
.PHONY : main.cpp.s

read_data.o: read_data.cpp.o

.PHONY : read_data.o

# target to build an object file
read_data.cpp.o:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/read_data.cpp.o
.PHONY : read_data.cpp.o

read_data.i: read_data.cpp.i

.PHONY : read_data.i

# target to preprocess a source file
read_data.cpp.i:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/read_data.cpp.i
.PHONY : read_data.cpp.i

read_data.s: read_data.cpp.s

.PHONY : read_data.s

# target to generate assembly for a file
read_data.cpp.s:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/read_data.cpp.s
.PHONY : read_data.cpp.s

test_shortest_paths.o: test_shortest_paths.cpp.o

.PHONY : test_shortest_paths.o

# target to build an object file
test_shortest_paths.cpp.o:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/test_shortest_paths.cpp.o
.PHONY : test_shortest_paths.cpp.o

test_shortest_paths.i: test_shortest_paths.cpp.i

.PHONY : test_shortest_paths.i

# target to preprocess a source file
test_shortest_paths.cpp.i:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/test_shortest_paths.cpp.i
.PHONY : test_shortest_paths.cpp.i

test_shortest_paths.s: test_shortest_paths.cpp.s

.PHONY : test_shortest_paths.s

# target to generate assembly for a file
test_shortest_paths.cpp.s:
	$(MAKE) -f CMakeFiles/main.exe.dir/build.make CMakeFiles/main.exe.dir/test_shortest_paths.cpp.s
.PHONY : test_shortest_paths.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... main.exe"
	@echo "... Nexullance_IT.o"
	@echo "... Nexullance_IT.i"
	@echo "... Nexullance_IT.s"
	@echo "... helpers.o"
	@echo "... helpers.i"
	@echo "... helpers.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... read_data.o"
	@echo "... read_data.i"
	@echo "... read_data.s"
	@echo "... test_shortest_paths.o"
	@echo "... test_shortest_paths.i"
	@echo "... test_shortest_paths.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

